### ISSUE TITLE
add incoming relations to lexical units / synsets

### ISSUE THREAD

**Issue by Blubberli** [Germanet-sfs/GermaNetApi#5]
for one-directional relations, incoming relations to a given lexical unit might be interesting. this information so far cannot be extracted. adding one map "incomingRelations" with relation:(lexical unit/ Synset) would make that possible.

**Comment by m-hinrichs** [comment]
Additional methods to fetch relations for both synsets and lexunits are included, where the direction (incoming or outgoing) can be specified.
