### ISSUE TITLE
Inconsistent handling of GNROOT between versions

### ISSUE THREAD

**Issue by matlaj** [Germanet-sfs/GermaNetApi#7]
On version 13.1.0, both `germanet.getSynsets()` and `germanet.getSynsets("GNROOT")` return the synset for GNROOT.
On version 13.2.1, however, only `germanet.getSynsets()` returns GNROOT -- `germanet.getSynsets("GNROOT")` returns an empty list.

Is this change intentional?
(It seems the reason for the missing synset is [here](https://github.com/Germanet-sfs/GermaNetApi/blob/eadc325cef065c31678031ee151b1c5ae5b517d8/src/main/java/de/tuebingen/uni/sfs/germanet/api/GermaNet.java#L425).)

**Comment by m-hinrichs** [comment]
The root synset was removed from the maps because having it there prevented the semantic similarity methods from working correctly.

Another way to get the root synset is: `germanet.getSynsetByID(GermaNet.GNROOT_ID);`
Will that work for you?

**Comment by matlaj** [comment]
Yes, I was just wondering if this is an unintended change and the old behavior might get reintroduced in a later version, or I can expect the API to work like this from now on. Thank you.
